title: 2147483647 blog
description: 2147483647 blog
author: Hyeonsoft
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/hyeonsoft
about: student

baseurl: "https://hyeonsoft.github.io"
url: "https://hyeonsoft.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: null

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
